name: Deploy to EKS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region ap-south-1 \
        | docker login --username AWS --password-stdin \
          <AWS_ACCOUNT_ID>.dkr.ecr.ap-south-1.amazonaws.com

    - name: Build and push Docker image
      run: |
        docker build -t eks-demo .
        docker tag eks-demo:latest <AWS_ACCOUNT_ID>.dkr.ecr.ap-south-1.amazonaws.com/eks-demo:latest
        docker push <AWS_ACCOUNT_ID>.dkr.ecr.ap-south-1.amazonaws.com/eks-demo:latest

    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig --name eks-dev --region ap-south-1

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/
